package JSX.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import JSX.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.JSXFile:
        return new JSXFile_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(MetaAdapterFactory.getConcept(0xde8c8c5ea61e4f8bL, 0xbbd9356ad0debde1L, 0x3bf465b8a90b043eL, "JSX.structure.JSXFile"))) {
        String fname = getFileName_JSXFile(root);
        String ext = getFileExtension_JSXFile(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_JSXFile(SNode node) {
    return node.getName();
  }
  private static String getFileExtension_JSXFile(SNode node) {
    return "jsx";
  }
}
